---
 - name:  Install mc 
   apt:
    name: mc
    state: present
    
 - name:  Install net-tools 
   apt:
    name: net-tools
    state: present

#  - name:  Copy config 
#    ansible.builtin.copy:
#     src: roles/vsftpd/files/vsftpd.conf 
#     dest: /etc/vsftpd.conf

#  - name:  Run vsfrpd 
#    ansible.builtin.service:
#     name: vsftpd 
#     state: started
