---
 - name: Add key
   apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

 - name: Ensure the repository is configured
   apt_repository: 
        repo: deb https://download.docker.com/linux/ubuntu focal stable 
        state: present

 - name:  Update cache
   apt:
        update_cache: yes
        state: latest

 - name: Install docker
   apt:
        name: docker-ce
        state: present

 - name: Start & Enable Jenkins
   service: 
        name: docker
        state: started        